In [1]:
import mysql.connector
from sqlalchemy import create_engine
import pandas as pd

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="employees"
)

engine = create_engine("mysql+pymysql://root:@localhost/employees")

print("Connected Successfully")

Connected Successfully

In [2]:
query = "Select * from departments;"
df = pd.read_sql(query, engine)
df

  dept_no           dept_name
0    d009    Customer Service
1    d005         Development
2    d002             Finance
3    d003     Human Resources
4    d001           Marketing
5    d004          Production
6    d006  Quality Management
7    d008            Research
8    d007               Sales

In [7]:
# Display all records from the employees table

query = "Select * from employees limit 10;"
df = pd.read_sql(query, engine)
df

   emp_no  birth_date first_name  last_name gender   hire_date
0   10001  1953-09-02     Georgi    Facello      M  1986-06-26
1   10002  1964-06-02    Bezalel     Simmel      F  1985-11-21
2   10003  1959-12-03      Parto    Bamford      M  1986-08-28
3   10004  1954-05-01  Chirstian    Koblick      M  1986-12-01
4   10005  1955-01-21    Kyoichi   Maliniak      M  1989-09-12
5   10006  1953-04-20     Anneke    Preusig      F  1989-06-02
6   10007  1957-05-23    Tzvetan  Zielinski      F  1989-02-10
7   10008  1958-02-19     Saniya   Kalloufi      M  1994-09-15
8   10009  1952-04-19     Sumant       Peac      F  1985-02-18
9   10010  1963-06-01  Duangkaew   Piveteau      F  1989-08-24

In [9]:
# Display only emp_no, first_name, and last_name

query = "Select emp_no, first_name, last_name from employees limit 5;"
df = pd.read_sql(query, engine)
df

   emp_no first_name last_name
0   10001     Georgi   Facello
1   10002    Bezalel    Simmel
2   10003      Parto   Bamford
3   10004  Chirstian   Koblick
4   10005    Kyoichi  Maliniak

In [12]:
# Display all female employees.

query = "Select * from employees where gender = 'F' limit 5;"
df = pd.read_sql(query, engine)
df

   emp_no  birth_date first_name  last_name gender   hire_date
0   10002  1964-06-02    Bezalel     Simmel      F  1985-11-21
1   10006  1953-04-20     Anneke    Preusig      F  1989-06-02
2   10007  1957-05-23    Tzvetan  Zielinski      F  1989-02-10
3   10009  1952-04-19     Sumant       Peac      F  1985-02-18
4   10010  1963-06-01  Duangkaew   Piveteau      F  1989-08-24

In [13]:
# Display all male employees.

query = "Select * from employees where gender = 'M' limit 5;"
df = pd.read_sql(query, engine)
df

   emp_no  birth_date first_name last_name gender   hire_date
0   10001  1953-09-02     Georgi   Facello      M  1986-06-26
1   10003  1959-12-03      Parto   Bamford      M  1986-08-28
2   10004  1954-05-01  Chirstian   Koblick      M  1986-12-01
3   10005  1955-01-21    Kyoichi  Maliniak      M  1989-09-12
4   10008  1958-02-19     Saniya  Kalloufi      M  1994-09-15

In [15]:
# Display employees hired in the year 1986.

query = "Select * from employees where year(hire_date) = 1986;"
df = pd.read_sql(query, engine)
df

       emp_no  birth_date first_name last_name gender   hire_date
0       10001  1953-09-02     Georgi   Facello      M  1986-06-26
1       10003  1959-12-03      Parto   Bamford      M  1986-08-28
2       10004  1954-05-01  Chirstian   Koblick      M  1986-12-01
3       10053  1954-09-13     Sanjiv  Zschoche      F  1986-02-04
4       10066  1952-11-13       Kwee  Schusler      M  1986-02-26
...       ...         ...        ...       ...    ...         ...
36145  499940  1952-02-12      Yolla     Auria      M  1986-04-25
36146  499946  1956-08-10     Barton   Soicher      F  1986-02-21
36147  499982  1954-08-25   Mohammed  Pleszkun      M  1986-02-21
36148  499988  1962-09-28   Bangqing   Kleiser      F  1986-06-06
36149  499997  1961-08-03    Berhard    Lenart      M  1986-04-21

[36150 rows x 6 columns]

In [18]:
# Display the details of employee number 10001.

query = "Select * from employees where emp_no = '10001';"
df = pd.read_sql(query, engine)
df

   emp_no  birth_date first_name last_name gender   hire_date
0   10001  1953-09-02     Georgi   Facello      M  1986-06-26

In [21]:
# Display employees whose first name is Georgi.

query = "Select * from employees where first_name = 'Georgi';"
df = pd.read_sql(query, engine)
df

     emp_no  birth_date first_name  last_name gender   hire_date
0     10001  1953-09-02     Georgi    Facello      M  1986-06-26
1     10909  1954-11-11     Georgi    Atchley      M  1985-04-21
2     11029  1962-07-12     Georgi   Itzfeldt      M  1992-12-27
3     11430  1957-01-23     Georgi    Klassen      M  1996-02-27
4     12157  1960-03-30     Georgi    Barinka      M  1985-06-04
..      ...         ...        ...        ...    ...         ...
248  497046  1959-12-15     Georgi    Rouquie      M  1987-10-15
249  497592  1959-04-22     Georgi     Ariola      M  1986-03-27
250  497609  1956-06-19     Georgi    Rosiles      M  1986-02-24
251  498809  1961-10-24     Georgi   Ferriere      M  1993-02-21
252  499814  1960-12-28     Georgi  Wielonsky      M  1989-01-31

[253 rows x 6 columns]

In [22]:
# Display employees whose last name Facello.

query = "Select * from employees where last_name = 'Facello';"
df = pd.read_sql(query, engine)
df

     emp_no  birth_date first_name last_name gender   hire_date
0     10001  1953-09-02     Georgi   Facello      M  1986-06-26
1     10327  1954-04-01      Roded   Facello      M  1987-09-18
2     12751  1964-07-06      Nahum   Facello      M  1995-01-09
3     15346  1959-09-26       Kirk   Facello      F  1991-12-07
4     15685  1958-07-12    Kasturi   Facello      M  1992-03-13
..      ...         ...        ...       ...    ...         ...
181  486102  1956-09-08      Arfst   Facello      F  1996-07-29
182  486829  1953-10-11       Mary   Facello      M  1998-02-13
183  487188  1959-02-20    Richara   Facello      M  1985-08-31
184  488569  1955-11-15     Satoru   Facello      M  1993-03-20
185  493549  1960-04-17  Achilleas   Facello      F  1991-11-27

[186 rows x 6 columns]

In [23]:
# Display the first 20 employees.

query = "Select * from employees limit 20;"
df = pd.read_sql(query, engine)
df

    emp_no  birth_date first_name    last_name gender   hire_date
0    10001  1953-09-02     Georgi      Facello      M  1986-06-26
1    10002  1964-06-02    Bezalel       Simmel      F  1985-11-21
2    10003  1959-12-03      Parto      Bamford      M  1986-08-28
3    10004  1954-05-01  Chirstian      Koblick      M  1986-12-01
4    10005  1955-01-21    Kyoichi     Maliniak      M  1989-09-12
5    10006  1953-04-20     Anneke      Preusig      F  1989-06-02
6    10007  1957-05-23    Tzvetan    Zielinski      F  1989-02-10
7    10008  1958-02-19     Saniya     Kalloufi      M  1994-09-15
8    10009  1952-04-19     Sumant         Peac      F  1985-02-18
9    10010  1963-06-01  Duangkaew     Piveteau      F  1989-08-24
10   10011  1953-11-07       Mary        Sluis      F  1990-01-22
11   10012  1960-10-04   Patricio    Bridgland      M  1992-12-18
12   10013  1963-06-07  Eberhardt       Terkki      M  1985-10-20
13   10014  1956-02-12      Berni        Genin      M  1987-03-11
14   10015  1959-08-19   Guoxiang    Nooteboom      M  1987-07-02
15   10016  1961-05-02   Kazuhito  Cappelletti      M  1995-01-27
16   10017  1958-07-06  Cristinel    Bouloucos      F  1993-08-03
17   10018  1954-06-19   Kazuhide         Peha      F  1987-04-03
18   10019  1953-01-23    Lillian      Haddadi      M  1999-04-30
19   10020  1952-12-24     Mayuko      Warwick      M  1991-01-26

In [24]:
# Count of total number of employees.

query = "Select Count(*) from employees;"
df = pd.read_sql(query, engine)
df

   Count(*)
0    300024

In [25]:
# Display employees hired after 1990-01-01.

query = "Select * from employees where year(hire_date) >= '1990-01-01';"
df = pd.read_sql(query, engine)
df

        emp_no  birth_date first_name    last_name gender   hire_date
0        10008  1958-02-19     Saniya     Kalloufi      M  1994-09-15
1        10011  1953-11-07       Mary        Sluis      F  1990-01-22
2        10012  1960-10-04   Patricio    Bridgland      M  1992-12-18
3        10016  1961-05-02   Kazuhito  Cappelletti      M  1995-01-27
4        10017  1958-07-06  Cristinel    Bouloucos      F  1993-08-03
...        ...         ...        ...          ...    ...         ...
135222  499994  1952-02-26      Navin      Argence      F  1990-04-24
135223  499995  1958-09-24     Dekang     Lichtner      F  1993-01-12
135224  499996  1953-03-07       Zito         Baaz      M  1990-09-27
135225  499998  1956-09-05   Patricia      Breugel      M  1993-10-13
135226  499999  1958-05-01     Sachin      Tsukuda      M  1997-11-30

[135227 rows x 6 columns]

In [33]:
# Display employees hired before 1985-01-01.

query = "Select * from employees where year(hire_date) <= '1985-01-01';"
df = pd.read_sql(query, engine)
df

       emp_no  birth_date first_name last_name gender   hire_date
0       10002  1964-06-02    Bezalel    Simmel      F  1985-11-21
1       10009  1952-04-19     Sumant      Peac      F  1985-02-18
2       10013  1963-06-07  Eberhardt    Terkki      M  1985-10-20
3       10029  1956-12-13      Otmar    Herbst      M  1985-11-20
4       10048  1963-07-11    Florian  Syrotiuk      M  1985-02-24
...       ...         ...        ...       ...    ...         ...
35311  499965  1961-12-07    Ronghao    Morrow      F  1985-05-26
35312  499966  1955-12-04    Mihalis  Crabtree      F  1985-06-13
35313  499984  1959-08-31    Kaijung    Rodham      M  1985-09-11
35314  499986  1952-07-22     Nathan     Ranta      F  1985-08-11
35315  499990  1963-11-03     Khaled   Kohling      M  1985-10-10

[35316 rows x 6 columns]

In [39]:
# display employees whose first name starts with A.

query = """ SELECT * FROM employees WHERE first_name LIKE 'A%%'; """
df = pd.read_sql(query, engine)
df

       emp_no  birth_date  first_name  last_name gender   hire_date
0       10006  1953-04-20      Anneke    Preusig      F  1989-06-02
1       10033  1956-11-14        Arif      Merlo      M  1987-03-18
2       10035  1953-02-08       Alain  Chappelet      M  1988-09-05
3       10036  1959-08-10  Adamantios  Portugali      M  1992-01-03
4       10039  1959-10-01   Alejandro    Brender      M  1988-01-19
...       ...         ...         ...        ...    ...         ...
22034  499905  1952-07-13   Annemarie     Hasham      M  1990-04-10
22035  499907  1954-04-18        Arnd    Garnham      M  1986-01-12
22036  499924  1963-06-08       Angus       Swan      M  1998-08-04
22037  499930  1959-06-19    Ayakannu     Beerel      M  1988-03-23
22038  499952  1953-11-19        Aron  Lindqvist      M  1990-01-07

[22039 rows x 6 columns]

In [40]:
# Display employees whose last name ends with son.

query = """ SELECT * FROM employees WHERE last_name LIKE '%%son'; """
df = pd.read_sql(query, engine)
df

      emp_no  birth_date first_name  last_name gender   hire_date
0      10100  1953-04-21   Hironobu  Haraldson      F  1987-09-21
1      10119  1960-12-01   Domenick   Peltason      M  1986-03-14
2      10130  1955-04-27     Nishit  Casperson      M  1988-06-21
3      10217  1954-07-07    Yongmin     Roison      F  1986-05-12
4      10274  1957-08-23     Dmitri    Pearson      F  1991-04-21
...      ...         ...        ...        ...    ...         ...
2706  499338  1953-12-04        Goa  Haraldson      F  1992-05-19
2707  499373  1954-04-12      Maria  Haraldson      M  1992-06-07
2708  499481  1959-03-05  Masamitsu   Matheson      M  1990-02-27
2709  499715  1961-11-14   Takanari   Peltason      M  1994-09-26
2710  499789  1961-03-29    Chuanti    Jonsson      M  1987-07-20

[2711 rows x 6 columns]

In [42]:
# Display employees whose first name contains an.

query = """ Select * from employees where first_name LIKE '%%an%%';"""
df = pd.read_sql(query, engine)
df

       emp_no  birth_date first_name  last_name gender   hire_date
0       10004  1954-05-01  Chirstian    Koblick      M  1986-12-01
1       10006  1953-04-20     Anneke    Preusig      F  1989-06-02
2       10007  1957-05-23    Tzvetan  Zielinski      F  1989-02-10
3       10008  1958-02-19     Saniya   Kalloufi      M  1994-09-15
4       10009  1952-04-19     Sumant       Peac      F  1985-02-18
...       ...         ...        ...        ...    ...         ...
47291  499970  1963-03-25      Danai    Hedayat      M  1994-08-06
47292  499978  1960-03-29  Chiranjit    Kuzuoka      M  1990-05-24
47293  499986  1952-07-22     Nathan      Ranta      F  1985-08-11
47294  499988  1962-09-28   Bangqing    Kleiser      F  1986-06-06
47295  499995  1958-09-24     Dekang   Lichtner      F  1993-01-12

[47296 rows x 6 columns]

In [44]:
# ---------------------------- SALARY TABLE -----------------------------

In [50]:
# Display all salary records

query = "SELECT * FROM salaries limit 5;"
df = pd.read_sql(query, engine)
df

   emp_no  salary   from_date     to_date
0   10001   60117  1986-06-26  1987-06-26
1   10001   62102  1987-06-26  1988-06-25
2   10001   66074  1988-06-25  1989-06-25
3   10001   66596  1989-06-25  1990-06-25
4   10001   66961  1990-06-25  1991-06-25

In [51]:
# Display all salary records of employees 10001.

query = "SELECT * FROM salaries where emp_no = '10001';"
df = pd.read_sql(query, engine)
df

    emp_no  salary   from_date     to_date
0    10001   60117  1986-06-26  1987-06-26
1    10001   62102  1987-06-26  1988-06-25
2    10001   66074  1988-06-25  1989-06-25
3    10001   66596  1989-06-25  1990-06-25
4    10001   66961  1990-06-25  1991-06-25
5    10001   71046  1991-06-25  1992-06-24
6    10001   74333  1992-06-24  1993-06-24
7    10001   75286  1993-06-24  1994-06-24
8    10001   75994  1994-06-24  1995-06-24
9    10001   76884  1995-06-24  1996-06-23
10   10001   80013  1996-06-23  1997-06-23
11   10001   81025  1997-06-23  1998-06-23
12   10001   81097  1998-06-23  1999-06-23
13   10001   84917  1999-06-23  2000-06-22
14   10001   85112  2000-06-22  2001-06-22
15   10001   85097  2001-06-22  2002-06-22
16   10001   88958  2002-06-22  9999-01-01

In [53]:
# Display salaries greater than 80000.

query = """SELECT * FROM salaries where salary > '80000';"""
df = pd.read_sql(query, engine)
df

        emp_no  salary   from_date     to_date
0        10001   80013  1996-06-23  1997-06-23
1        10001   81025  1997-06-23  1998-06-23
2        10001   81097  1998-06-23  1999-06-23
3        10001   84917  1999-06-23  2000-06-22
4        10001   85112  2000-06-22  2001-06-22
...        ...     ...         ...         ...
491461  499988  102085  2001-07-22  2001-10-09
491462  499992   80389  2002-05-06  9999-01-01
491463  499997   82424  1999-08-27  2000-08-26
491464  499997   82750  2000-08-26  2001-08-26
491465  499997   83441  2001-08-26  9999-01-01

[491466 rows x 4 columns]

In [57]:
# Find the highest salary.

query = """ Select MAX(salary) AS Highest_Salary from salaries;"""
df = pd.read_sql(query, engine)
df

   Highest_Salary
0          158220

In [58]:
# Find the lowest salary.

query = """ Select Min(salary) AS lowest_Salary from salaries;"""
df = pd.read_sql(query, engine)
df

   lowest_Salary
0          38623

In [59]:
# Find the average salary.

query = """ Select AVG(salary) AS average_Salary from salaries;"""
df = pd.read_sql(query, engine)
df

   average_Salary
0      63810.7448

In [62]:
# Display the top 10 higest salary.

query = """ Select salary from salaries order by salary desc limit 10 ;"""
df = pd.read_sql(query, engine)
df

   salary
0  158220
1  157821
2  156286
3  155709
4  155513
5  155377
6  155190
7  154888
8  154885
9  154459

In [64]:
# Find the third higest salary

query = """
SELECT MAX(salary) AS third_highest_salary
FROM salaries
WHERE salary < (
    SELECT MAX(salary)
    FROM salaries
    WHERE salary < (
        SELECT MAX(salary)
        FROM salaries
    )
);
"""

df = pd.read_sql(query, engine)
df

   third_highest_salary
0                156286

In [66]:
# Find the fifth higest salary

query = """
Select DISTINCT salary from salaries ORDER BY salary desc limit 1 OFFSET 4;
"""

df = pd.read_sql(query, engine)
df

   salary
0  155513

In [67]:
# -------------------------------- Department Table ----------------------

In [69]:
# Display all departments table record.

query = """Select * from departments;"""

df = pd.read_sql(query, engine)
df

  dept_no           dept_name
0    d009    Customer Service
1    d005         Development
2    d002             Finance
3    d003     Human Resources
4    d001           Marketing
5    d004          Production
6    d006  Quality Management
7    d008            Research
8    d007               Sales

In [70]:
# Display all department names.

query = """Select dept_name from departments;"""

df = pd.read_sql(query, engine)
df

            dept_name
0    Customer Service
1         Development
2             Finance
3     Human Resources
4           Marketing
5          Production
6  Quality Management
7            Research
8               Sales

In [71]:
# count the total number of departments.

query = """Select COUNT(*) dept_name from departments;"""

df = pd.read_sql(query, engine)
df

   dept_name
0          9

In [72]:
# Display the department whose name is "Development".

query = """Select * from departments where dept_name = 'Development';"""

df = pd.read_sql(query, engine)
df

  dept_no    dept_name
0    d005  Development

In [73]:
# =================================== JOIN QUESTIONS ===============================

In [74]:
query = """Select * from employees limit 5;"""

df = pd.read_sql(query, engine)
df

   emp_no  birth_date first_name last_name gender   hire_date
0   10001  1953-09-02     Georgi   Facello      M  1986-06-26
1   10002  1964-06-02    Bezalel    Simmel      F  1985-11-21
2   10003  1959-12-03      Parto   Bamford      M  1986-08-28
3   10004  1954-05-01  Chirstian   Koblick      M  1986-12-01
4   10005  1955-01-21    Kyoichi  Maliniak      M  1989-09-12

In [75]:
query = """Select * from departments limit 5;"""

df = pd.read_sql(query, engine)
df

  dept_no         dept_name
0    d009  Customer Service
1    d005       Development
2    d002           Finance
3    d003   Human Resources
4    d001         Marketing

In [76]:
query = """Select * from dept_emp limit 5;"""

df = pd.read_sql(query, engine)
df

   emp_no dept_no   from_date     to_date
0   10001    d005  1986-06-26  9999-01-01
1   10002    d007  1996-08-03  9999-01-01
2   10003    d004  1995-12-03  9999-01-01
3   10004    d004  1986-12-01  9999-01-01
4   10005    d003  1989-09-12  9999-01-01

In [79]:
# Display employees name with depart name.

# tables - employees, dept_emp, departments

query = """
            Select
            e.emp_no,
            e.first_name,
            e.last_name,
            d.dept_name 
                    from employees e
            JOIN dept_emp de
                    ON e.emp_no = de.emp_no
            JOIN departments d
                    ON de.dept_no = d.dept_no
            limit 5;"""

df = pd.read_sql(query, engine)
df

   emp_no first_name    last_name         dept_name
0   10011       Mary        Sluis  Customer Service
1   10038       Huan        Lortz  Customer Service
2   10049      Basil       Tramer  Customer Service
3   10060   Breannda  Billingsley  Customer Service
4   10088   Jungsoon     Syrzycki  Customer Service

In [81]:
# Display employee name with salary

# tables - employees , salaries

query = """
SELECT
    e.first_name,
    e.last_name,
    s.salary
FROM employees e
JOIN salaries s
    ON e.emp_no = s.emp_no;
"""

df = pd.read_sql(query, engine)
df

        first_name last_name  salary
0           Georgi   Facello   60117
1           Georgi   Facello   62102
2           Georgi   Facello   66074
3           Georgi   Facello   66596
4           Georgi   Facello   66961
...            ...       ...     ...
2844042     Sachin   Tsukuda   63707
2844043     Sachin   Tsukuda   67043
2844044     Sachin   Tsukuda   70745
2844045     Sachin   Tsukuda   74327
2844046     Sachin   Tsukuda   77303

[2844047 rows x 3 columns]

In [82]:
# Display employee name with titles

# tables - employees , titles

query = """
SELECT
    e.first_name,
    e.last_name,
    t.title
FROM employees e
JOIN titles t
    ON e.emp_no = t.emp_no;
"""

df = pd.read_sql(query, engine)
df

       first_name last_name            title
0          Georgi   Facello  Senior Engineer
1         Bezalel    Simmel            Staff
2           Parto   Bamford  Senior Engineer
3       Chirstian   Koblick         Engineer
4       Chirstian   Koblick  Senior Engineer
...           ...       ...              ...
443303    Berhard    Lenart         Engineer
443304    Berhard    Lenart  Senior Engineer
443305   Patricia   Breugel     Senior Staff
443306   Patricia   Breugel            Staff
443307     Sachin   Tsukuda         Engineer

[443308 rows x 3 columns]

In [85]:
# Display employee name, department name, and salary current date.

# tables -- employees, dept_emp, depatments, salaries

query = """
SELECT
    e.first_name,
    e.last_name,
    d.dept_name,
    s.salary
FROM employees e
JOIN dept_emp de
    ON e.emp_no = de.emp_no
JOIN departments d
    ON de.dept_no = d.dept_no
JOIN salaries s
    ON e.emp_no = s.emp_no
WHERE de.to_date = '9999-01-01'
AND s.to_date = '9999-01-01'
LIMIt 10;
"""

df = pd.read_sql(query, engine)
df

  first_name    last_name         dept_name  salary
0       Huan        Lortz  Customer Service   64254
1      Basil       Tramer  Customer Service   51326
2   Breannda  Billingsley  Customer Service   93188
3   Jungsoon     Syrzycki  Customer Service   98003
4   Yuichiro        Swick  Customer Service   61070
5     Kayoko     Valtorta  Customer Service   77310
6    Babette        Lamba  Customer Service   67619
7      Maren       Hutton  Customer Service   67794
8    Abdulah    Thibadeau  Customer Service   50766
9     Jagoda    Braunmuhl  Customer Service   72497

In [86]:
# ================================= GROUP BY =============================

In [88]:
# Count employees in each department

query = """ SELECT 
d.dept_name,
COUNT(e.emp_no) AS total_employees
FROM departments d
JOIN dept_emp de
ON d.dept_no = de.dept_no
JOIN employees e
ON de.emp_no = e.emp_no
GROUP BY d.dept_name;"""

df = pd.read_sql(query, engine)
df

            dept_name  total_employees
0    Customer Service            23580
1         Development            85707
2             Finance            17346
3     Human Resources            17786
4           Marketing            20211
5          Production            73485
6  Quality Management            20117
7            Research            21126
8               Sales            52245

In [90]:
# Find theb Average Salary in each department.

query = """
SELECT 
d.dept_name,
ROUND(AVG(s.salary), 2) as average_salary
FROM departments d
JOIN dept_emp de
    ON d.dept_no = de.dept_no
JOIN employees e
    ON de.emp_no = e.emp_no
JOIN salaries s
    ON e.emp_no = s.emp_no
GROUP BY d.dept_name;"""

df = pd.read_sql(query, engine)
df

            dept_name  average_salary
0    Customer Service        58770.37
1         Development        59478.90
2             Finance        70489.36
3     Human Resources        55574.88
4           Marketing        71913.20
5          Production        59605.48
6  Quality Management        57251.27
7            Research        59665.18
8               Sales        80667.61

In [91]:
# Find the Maxmium Salary of each department.

query = """
SELECT 
d.dept_name,
MAX(s.salary) as maximum_salary
FROM departments d
JOIN dept_emp de
    ON d.dept_no = de.dept_no
JOIN employees e
    ON de.emp_no = e.emp_no
JOIN salaries s
    ON e.emp_no = s.emp_no
GROUP BY d.dept_name;"""

df = pd.read_sql(query, engine)
df

            dept_name  maximum_salary
0    Customer Service          144866
1         Development          144434
2             Finance          142395
3     Human Resources          141953
4           Marketing          145128
5          Production          138273
6  Quality Management          132103
7            Research          130211
8               Sales          158220

In [92]:
# Find the Minmum Salary of each department.

query = """
SELECT 
d.dept_name,
Min(s.salary) as minimum_salary
FROM departments d
JOIN dept_emp de
    ON d.dept_no = de.dept_no
JOIN employees e
    ON de.emp_no = e.emp_no
JOIN salaries s
    ON e.emp_no = s.emp_no
GROUP BY d.dept_name;"""

df = pd.read_sql(query, engine)
df

            dept_name  minimum_salary
0    Customer Service           38836
1         Development           38849
2             Finance           38812
3     Human Resources           38735
4           Marketing           39127
5          Production           38623
6  Quality Management           38786
7            Research           38851
8               Sales           39169

In [93]:
# Display all employees whose title is "Senior Engineer".

query = """
SELECT 
    e.emp_no,
    e.first_name,
    e.last_name,
    t.title
from employees e
JOIN titles t
    ON e.emp_no = t.emp_no
Where title = 'Senior engineer';"""
df = pd.read_sql(query, engine)
df

       emp_no first_name last_name            title
0       10001     Georgi   Facello  Senior Engineer
1       10003      Parto   Bamford  Senior Engineer
2       10004  Chirstian   Koblick  Senior Engineer
3       10006     Anneke   Preusig  Senior Engineer
4       10009     Sumant      Peac  Senior Engineer
...       ...        ...       ...              ...
97745  499964      Randy    Matzov  Senior Engineer
97746  499972     Katsuo    Leuchs  Senior Engineer
97747  499984    Kaijung    Rodham  Senior Engineer
97748  499996       Zito      Baaz  Senior Engineer
97749  499997    Berhard    Lenart  Senior Engineer

[97750 rows x 4 columns]

In [94]:
# Display employees working in the Development department

query = """
SELECT 
    e.emp_no,
    e.first_name,
    e.last_name,
    d.dept_name
from employees e
JOIN dept_emp de
    ON e.emp_no = de.emp_no
JOIN departments d
    ON de.dept_no = d.dept_no
where dept_name = 'development';"""


df = pd.read_sql(query, engine)
df

       emp_no first_name      last_name    dept_name
0       10001     Georgi        Facello  Development
1       10006     Anneke        Preusig  Development
2       10008     Saniya       Kalloufi  Development
3       10012   Patricio      Bridgland  Development
4       10014      Berni          Genin  Development
...       ...        ...            ...          ...
85702  499972     Katsuo         Leuchs  Development
85703  499973      Lobel        Taubman  Development
85704  499979  Prasadram  Waleschkowski  Development
85705  499990     Khaled        Kohling  Development
85706  499997    Berhard         Lenart  Development

[85707 rows x 4 columns]

In [ ]:
# Display employees earning more than the average salary.

query = """
SELECT 
    e.emp_no, 
    e.first_name,
    e.last_name,
    s.salary
FROM employees e
JOIN salaries s
    ON e.emp_no = s.emp_no
WHERE s.salary > (SELECT AVG(s.salary) FROM salaries) limit 10;"""
df = pd.read_sql(query, engine)
df

In [ ]:
# Display employee name, deaprtment, current title, current salary

query = """
SELECT 
    e.emp_no,
    e.first_name,
    e.last_name,
    d.dept_name,
    t.title,
    s.salary
FROM employees e
JOIN dept_emp de
     ON e.emp_no = de.emp_no
JOIN departments d
     ON de.dept_no = d.dept_no
JOIN titles t
    ON e.emp_no = t.emp_no
JOIN salaries s
    ON e.emp_no = s.emp_no limit 10; """
df = pd.read_sql(query, engine)
df

In [2]:
# Find the second highest salary

query = """
SELECT MAX(salary) AS second_highest_salary from salaries where salary < (SELECT MAX(salary) FROM salaries);"""
df = pd.read_sql(query, engine)
df

   second_highest_salary
0                 157821

In [ ]:
# Find the third highest salary

query = """
SELECT DISTINCT salary AS third_higest_salary FROM salaries ORDER BY salary desc limit 1 OFFSET 2;"""
df = pd.read_sql(query, engine)
df

In [ ]:
# Find top 5 highest paid employees.

query = """ SELECT 
    e.emp_no,
    e.first_name,
    e.last_name,
    MAX(s.salary) As salary
FROM employees e
JOIN salaries s
    ON e.emp_no = s.emp_no
ORDER BY s.salary DESC limit 5; """
df = pd.read_sql(query, engine)
df

In [ ]:
# Find the highest paid employee in each department

query = """
SELECT 
    e.emp_no,
    e.first_name,
    e.last_name,
    d.dept_name, 
    s.salary
FROM employees e
JOIN dept_emp de
    ON e.emp_no = de.emp_no
JOIN departments d
    ON de.dept_no = d.dept_no
JOIN salaries s
    ON e.emp_no = s.emp_no
WHERE s.salary = (
                SELECT MAX(s2.salary) FROM salaries s2
                JOIN dept_emp de2
                ON s2.emp_no = de2.emp_no
                 WHERE de2.dept_no = d.dept_no);"""


df = pd.read_sql(query, engine)
df